openapi: 3.0.0
info:
  title: AiEnglishLearner API
  version: 1.0.0
  description: API for user authentication and profile management
  
servers:
  - url: https://api.example.com/v1
    description: Main API server

components:
  securitySchemes:
    GoogleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            profile: Access to user profile
            email: Access to user email
    AppleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://appleid.apple.com/auth/authorize
          tokenUrl: https://appleid.apple.com/auth/token
          scopes:
            name: Access to user name
            email: Access to user email

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the user
        email:
          type: string
          format: email
          description: User's email address
        username:
          type: string
          description: User's username
        avatarUrl:
          type: string
          format: uri
          description: URL to user's avatar image
      required:
        - id
        - email
        - username

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    AuthCallbackRequest:
      type: object
      properties:
        code:
          type: string
          description: Authorization code from provider
        state:
          type: string
          description: State parameter for CSRF protection
      required:
        - code

paths:
  /auth/google:
    get:
      summary: Initiate Google OAuth 2.0 Login
      description: Redirects to Google OAuth 2.0 authentication
      responses:
        '302':
          description: Redirects to Google authorization URL

  /auth/google/callback:
    get:
      summary: Google OAuth 2.0 Callback
      description: Handles Google OAuth 2.0 callback with authorization code
      parameters:
        - in: query
          name: code
          schema:
            type: string
          required: true
          description: Authorization code
        - in: query
          name: state
          schema:
            type: string
          description: State parameter for CSRF protections
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/apple:
    get:
      summary: Initiate Apple OAuth 2.0 Login
      description: Redirects to Apple OAuth 2.0 authentication
      responses:
        '302':
          description: Redirects to Apple authorization URL

  /auth/apple/callback:
    post:
      summary: Apple OAuth 2.0 Callback
      description: Handles Apple OAuth 2.0 callback with authorization code
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthCallbackRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user:
    put:
      summary: Update user profile
      description: Updates user's name and avatar
      security:
        - GoogleOAuth: []
        - AppleOAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: New username
                avatar:
                  type: string
                  format: binary
                  description: New avatar image file
      responses:
        '200':
          description: Successfully updated user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

security:
  - GoogleOAuth: []
  - AppleOAuth: []
